version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: cutiendaDB
    environment:
      MARIADB_ROOT_PASSWORD: amadopord1
      MYSQL_DATABASE: cutienda
      MARIADB_ROOT_PASSWORD_HASH:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD:
      MARIADB_RANDOM_ROOT_PASSWORD:
    ports:
      - "3307:3306"
    networks:
      mariadb_network:

  productos:
    build:
      context: productos
      dockerfile: Dockerfile
    container_name: productos_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/cutienda?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: amadopord1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    ports:
      - "8010:8010"  # Mapea el puerto 8010 de tu máquina al puerto 8010 del contenedor Spring Boot
    depends_on:
      - mariadb  # Asegura que mariadb esté levantado antes de arrancar el microservicio productos
    networks:
      mariadb_network:

  usuarios:
    build:
      context: usuarios
      dockerfile: Dockerfile
    container_name: usuarios_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/cutienda?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: amadopord1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    ports:
      - "8011:8011"  # Mapea el puerto 8010 de tu máquina al puerto 8010 del contenedor Spring Boot
    depends_on:
      - mariadb  # Asegura que mariadb esté levantado antes de arrancar el microservicio productos
    networks:
      mariadb_network:

  notificaciones:
    build:
      context: Notificaciones
      dockerfile: Dockerfile
    container_name: notificaciones_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/cutienda?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: amadopord1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    ports:
      - "8012:8012"  # Mapea el puerto 8010 de tu máquina al puerto 8010 del contenedor Spring Boot
    depends_on:
      - mariadb  # Asegura que mariadb esté levantado antes de arrancar el microservicio productos
    networks:
      mariadb_network:

  comentarios:
    build:
      context: ComentariosyValoraciones
      dockerfile: Dockerfile
    container_name: comentarios_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/cutienda?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: amadopord1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    ports:
      - "8013:8013"  # Mapea el puerto 8010 de tu máquina al puerto 8010 del contenedor Spring Boot
    depends_on:
      - mariadb  # Asegura que mariadb esté levantado antes de arrancar el microservicio productos
    networks:
      mariadb_network:

  frontend:
    build:
      context: frontend/cutienda-front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"  # Mapea el puerto 8010 de tu máquina al puerto 8010 del contenedor Spring Boot
    depends_on:
      - mariadb  # Asegura que mariadb esté levantado antes de arrancar el microservicio productos
    networks:
      mariadb_network:

networks:
  mariadb_network:
    driver: bridge
    external: false
