version: '3.8'

services:
  mysql:
    image: mysql:8.0 # Puedes cambiar a otra versión si es necesario
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: amadopord1
      MYSQL_DATABASE: cutienda # Cambia a tu nombre de base de datos si es necesario
      MYSQL_USER: MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: amadopord1
    ports:
      - "3307:3306" # Mapea el puerto para acceder desde tu máquina
    volumes:
      - mysql_data:/var/lib/mysql # Persiste los datos en un volumen
    restart: always # Reinicia automáticamente en caso de fallo

volumes:
  mysql_data:
